name: brainup
description: "BrAIn Up"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

    # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  another_xlider: ^3.0.2
  photo_view: ^0.15.0
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  audioplayers: ^6.5.0
  another_flushbar: ^1.12.30
  # Network
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.0
  http: ^1.4.0
  googleapis_auth: ^2.0.0
  google_generative_ai: ^0.4.7
  # Logger
  awesome_dio_interceptor: ^1.3.0
  colorize: ^3.0.0

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Dependency injection
  get_it: ^8.0.3

  # Navigation
  go_router: ^14.8.1

  # Storage
  shared_preferences: ^2.5.2
  drift: ^2.25.0
  drift_flutter: ^0.2.4
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5

  # Permission
  permission_handler: ^11.3.1

  # Firebase
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  firebase_crashlytics: ^4.3.1
  firebase_auth: ^5.5.4
  # Utilities
  equatable: ^2.0.7
  collection: ^1.18.0
  fluttertoast: ^8.2.10
  uuid: ^4.5.1
  flutter_image_compress: ^2.4.0
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  flutter_tts: ^4.2.3
  speech_to_text: ^7.0.0
  flutter_bloc: ^9.1.1
  shimmer_animation: ^2.2.2
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.4.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  riverpod_generator: ^2.6.5
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  drift_dev: ^2.26.0
  theme_tailor: ^3.0.2

flutter_gen:
  output: lib/presentation/resources/gen
  line_length: 120

  assets:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/colors/
    - assets/lotties/
    - assets/sound/
    - assets/strings/

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/itim.ttf
          weight: 400

flutter_native_splash:
  color: "#000000"
  image: assets/images/ic_splash.png
  color_dark: "#000000"
  image_dark: assets/images/ic_splash.png

  android_12:
    color: "#000000"
    icon_background_color_dark: "#000000"
    image: assets/images/ic_splash_12.png
    image_dark: assets/images/ic_splash_12.png
    icon_background_color: "#F8F7FC"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/ic_splash.png
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
  adaptive_icon_foreground: assets/images/ic_splash.png
  background_color_ios: "#000000"
